# Generated by Django 2.2.24 on 2022-02-28 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECGList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ECGlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ECGdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volt', models.CharField(max_length=10)),
                ('nomal', models.BooleanField()),
                ('time', models.DateField(auto_now=True)),
                ('abnomal', models.CharField(max_length=30)),
                ('ECGlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ECGList')),
            ],
        ),
    ]
