# Generated by Django 2.2.24 on 2022-03-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgdata',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
