# Generated by Django 2.2.24 on 2021-09-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='complet',
            new_name='complete',
        ),
    ]
